seo:
  site_name: Roast & Roam
  title:
  description:
  keywords:
  social_image:
  author:
  favicon_image:
social:
  instagram_username:
  facebook_url:
  twitter_username:
design:
  dark_color:  '#c59486;'
  medium_color: '#dec2ba;'
  light_color: '#f1f0ef;'
  dark-text_color: '#231f20;'
  light-text_color: '#ffffff;'
